[build]
  command = "npm run build"
  publish = "."

# Pretty URLs and form handling redirects
[[redirects]]
  from = "/contact"
  to   = "/contact.html"
  status = 200

[[redirects]]
  from = "/prayer"
  to   = "/prayer.html"
  status = 200

[[redirects]]
  from = "/thank-you"
  to   = "/thank-you.html"
  status = 200

# Catch-all for other pages
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 404